name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome lint
        run: bun run lint
        continue-on-error: true
        id: lint_check

      - name: Suggest lint fix
        if: steps.lint_check.outcome == 'failure'
        run: |
          echo "::error::Linting issues detected!"
          echo "::notice::Run 'bun run lint:fix' locally to auto-fix lint issues"
          exit 1

      - name: Run Biome format check
        run: bun run format:check
        continue-on-error: true
        id: format_check

      - name: Suggest format fix
        if: steps.format_check.outcome == 'failure'
        run: |
          echo "::error::Code formatting issues detected!"
          echo "::notice::Run 'bun run format' locally to auto-fix all formatting issues"
          exit 1

      - name: Type check
        run: bun run typecheck